Repository HYF-Class22/group1-hyf-rebuild, pull requests merged in 2024-02, with the labels that each got.

#5 constraints.md
  planning/constraints.md
Labels: md

#16 planning/development-strategy.md
  planning/development-strategy.md
Labels: md

#27 user-personas1
  planning/user-personas.md
Labels: group, md

#63 Footer2
  index.html
  styles/footer.css
Labels: HTML, CSS

#74 partners
  img/partner16.jpg
  img/partner17.png
  img/partner18.png
  index.html
  styles/partners.css
Labels: HTML, CSS

#80 add development strategy-partners
  planning/development-strategy.md
Labels: documentation, group, md

#82 add testimonials html and css
  planning/development-strategy.md
Labels: md
